### ISSUE TITLE
Bug related to user_management_service

### ISSUE THREAD

**Issue by onlinejudge95** [unofficialopensource-knit/api_gateway#28]
```
2021-06-05T16:23:12.287111+00:00 app[web.1]: 10.51.150.4:34376 - "POST /api/user/ HTTP/1.1" 500
2021-06-05T16:23:12.293339+00:00 app[web.1]: [2021-06-05 16:23:12 +0000] [7] [ERROR] Exception in ASGI application
2021-06-05T16:23:12.293340+00:00 app[web.1]: Traceback (most recent call last):
2021-06-05T16:23:12.293340+00:00 app[web.1]: File "/usr/local/lib/python3.9/site-packages/uvicorn/protocols/http/httptools_impl.py", line 371, in run_asgi
2021-06-05T16:23:12.293340+00:00 app[web.1]: result = await app(self.scope, self.receive, self.send)
2021-06-05T16:23:12.293341+00:00 app[web.1]: File "/usr/local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 59, in __call__
2021-06-05T16:23:12.293341+00:00 app[web.1]: return await self.app(scope, receive, send)
2021-06-05T16:23:12.293342+00:00 app[web.1]: File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 199, in __call__
2021-06-05T16:23:12.293342+00:00 app[web.1]: await super().__call__(scope, receive, send)
2021-06-05T16:23:12.293342+00:00 app[web.1]: File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line 112, in __call__
2021-06-05T16:23:12.293342+00:00 app[web.1]: await self.middleware_stack(scope, receive, send)
2021-06-05T16:23:12.293343+00:00 app[web.1]: File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
2021-06-05T16:23:12.293343+00:00 app[web.1]: raise exc from None
2021-06-05T16:23:12.293344+00:00 app[web.1]: File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
2021-06-05T16:23:12.293344+00:00 app[web.1]: await self.app(scope, receive, _send)
2021-06-05T16:23:12.293344+00:00 app[web.1]: File "/usr/local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 78, in __call__
2021-06-05T16:23:12.293344+00:00 app[web.1]: await self.app(scope, receive, send)
2021-06-05T16:23:12.293344+00:00 app[web.1]: File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
2021-06-05T16:23:12.293345+00:00 app[web.1]: raise exc from None
2021-06-05T16:23:12.293345+00:00 app[web.1]: File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
2021-06-05T16:23:12.293345+00:00 app[web.1]: await self.app(scope, receive, sender)
2021-06-05T16:23:12.293345+00:00 app[web.1]: File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 580, in __call__
2021-06-05T16:23:12.293346+00:00 app[web.1]: await route.handle(scope, receive, send)
2021-06-05T16:23:12.293346+00:00 app[web.1]: File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 241, in handle
2021-06-05T16:23:12.293346+00:00 app[web.1]: await self.app(scope, receive, send)
2021-06-05T16:23:12.293346+00:00 app[web.1]: File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 52, in app
2021-06-05T16:23:12.293347+00:00 app[web.1]: response = await func(request)
2021-06-05T16:23:12.293347+00:00 app[web.1]: File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 201, in app
2021-06-05T16:23:12.293347+00:00 app[web.1]: raw_response = await run_endpoint_function(
2021-06-05T16:23:12.293347+00:00 app[web.1]: File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 148, in run_endpoint_function
2021-06-05T16:23:12.293348+00:00 app[web.1]: return await dependant.call(**values)
2021-06-05T16:23:12.293348+00:00 app[web.1]: File "/usr/src/app/src/routers/user/routes.py", line 28, in create_user
2021-06-05T16:23:12.293348+00:00 app[web.1]: r = await async_client.post(url=url, json=data, headers=headers)
2021-06-05T16:23:12.293348+00:00 app[web.1]: File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1746, in post
2021-06-05T16:23:12.293348+00:00 app[web.1]: return await self.request(
2021-06-05T16:23:12.293349+00:00 app[web.1]: File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1425, in request
2021-06-05T16:23:12.293349+00:00 app[web.1]: response = await self.send(
2021-06-05T16:23:12.293349+00:00 app[web.1]: File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1510, in send
2021-06-05T16:23:12.293349+00:00 app[web.1]: response = await self._send_handling_auth(
2021-06-05T16:23:12.293349+00:00 app[web.1]: File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1545, in _send_handling_auth
2021-06-05T16:23:12.293350+00:00 app[web.1]: response = await self._send_handling_redirects(
2021-06-05T16:23:12.293350+00:00 app[web.1]: File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1579, in _send_handling_redirects
2021-06-05T16:23:12.293350+00:00 app[web.1]: response = await self._send_single_request(request, timeout)
2021-06-05T16:23:12.293350+00:00 app[web.1]: File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1620, in _send_single_request
2021-06-05T16:23:12.293350+00:00 app[web.1]: ) = await transport.handle_async_request(
2021-06-05T16:23:12.293350+00:00 app[web.1]: File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 274, in handle_async_request
2021-06-05T16:23:12.293351+00:00 app[web.1]: (
2021-06-05T16:23:12.293351+00:00 app[web.1]: File "/usr/local/lib/python3.9/contextlib.py", line 135, in __exit__
2021-06-05T16:23:12.293351+00:00 app[web.1]: self.gen.throw(type, value, traceback)
2021-06-05T16:23:12.293352+00:00 app[web.1]: File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 78, in map_httpcore_exceptions
2021-06-05T16:23:12.293352+00:00 app[web.1]: raise mapped_exc(message) from exc
2021-06-05T16:23:12.293352+00:00 app[web.1]: httpx.UnsupportedProtocol: Unsupported URL protocol ''
2021-06-05T16:23:12.295031+00:00 heroku[router]: at=info method=POST path="/api/user/" host=api-gateway-web.herokuapp.com request_id=c3cb8baf-53dc-4e47-b727-d03142c8f096 fwd="117.251.64.196" dyno=web.1 connect=1ms service=11ms status=500 bytes=193 protocol=https
```

**Comment by onlinejudge95** [comment]
The issue was that the `USER_MICROSERVICE_URL` was missing. The issue is fixed in https://github.com/unofficialopensource-knit/infrastructure-setup/pull/32
